### ISSUE TITLE
krktr1=input("ilk karakterin adını giriniz");

### ISSUE THREAD

**Issue by AoiKos1243** [sonsuzus/sonsuzus.github.io#85]
krktr1=input("ilk karakterin adını giriniz");
krktr2=input("ikinci karakterin adını giriniz");

print("Bir gün", krktr1, krktr2, "ye halı sahaya gelip gelemeyeceğini sormuş", krktr2, "hayır demiş.", krktr1, krktr2, 
"ye küsmüş çünkü onunla hiç ilgilenmediğini düşünmüş." ,"ertesi gün", krktr2, krktr1, "i oyuna çağırmış ve küslüğü bitirmiş.", " bu hikayede burada bitmiş." );

_Originally posted by @AoiKos1243 in https://github.com/sonsuzus/sonsuzus.github.io/discussions/84#discussioncomment-3841734_

**Comment by sonsuzus** [comment]
Buraya yapılmayacak, gönderdiğim linke lütfen.
